name: Production Pipeline
on:
  push:
    tags:
      - "*"
    branches:
      - "feature/github-ci"
jobs:
  build:
    name: Build Production
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 50
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.102.0"
      - name: Build Project
        run: hugo --gc --minify
      - name: Storing Artifacts
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: public
          path: public/
          retention-days: 1
  deploy:
    name: Deploy Production
    needs: build
    runs-on: ubuntu-18.04
    steps:
          - name: Download Artifacts
            uses: actions/download-artifact@v2
            with:
              name: public
              path: public/
          - name: Publish to Netlify
            uses: netlify/actions/cli@master
            with:
              args: deploy -p --dir=public
            env:
              NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}